version: '3.8'

services:
  # --- Kafka Service ---
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    user: root
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - ./data/kafka-confluent:/var/lib/kafka/data
    networks:
      - app-network

  # --- MongoDB Service ---
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes: [ "./data/mongo:/data/db" ]

  # --- MySQL Service ---
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dev_db
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes: [ "./data/mysql:/var/lib/mysql" ]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot_password"]
      timeout: 20s
      retries: 10

  # --- Producer Service ---
  producer:
    build: ./producer
    depends_on:
      - kafka
      - mongo
    environment:
      KAFKA_BROKER: kafka:29092
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

      MONGODB_URL: mongodb://mongo:27017
    networks:
      - app-network

  # --- Consumer Service ---
  consumer:
    build: ./consumer
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:29092
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      BOOTSTRAP_SERVERS: kafka:29092


      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: root
    networks:
      - app-network

  # --- Analytics API Service ---
  analytics-api:
    build: ./analytics-api
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge